name: '507'
channels:
  - conda-forge
  - defaults
dependencies:
  - async-generator==1.10
  - certifi==2021.5.30
  - cloudpickle==1.6.0
  - ipython-genutils==0.2.0
  - itables==0.3.0
  - jupytext==1.11.4
  - pandas==1.3.1
  - pandocfilters==1.4.2
  - pyparsing==2.4.7
  - PyYAML==5.4.1
  - rise==5.7.1
  - webencodings==0.5.1
  - wurlitzer==3.0.2
